### ISSUE TITLE
Provide a functional interface which doesn't pollute Function.prototype

### ISSUE THREAD

**Issue by chocolateboy** [kushal-likhi/operator-overloading-js#9]
Kudos for this! It looks like a well-thought-out implementation which avoids the obvious gotchas and is mindful of the scoping/performance issues which plague [other implementations](https://news.ycombinator.com/item?id=7852821)<sup>[\[1\]](#user-content-paperscript)</sup>, but I could never use it in a library or production code as it pollutes a host object (Function), which is considered a [no-no](http://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/) in JavaScript.

Have you considered providing a functional interface as well/instead e.g.:

```javascript
import overload from 'operator-overloading';

overload(() => {
    let c1 = new Complex(1, 2);
    let c2 = new Complex(3, 4);
    assert.equal(c1 + c2, '4+6i');
})();
```

The method could still be enabled explicitly [e.g.](https://github.com/arturadib/shelljs#global-vs-local):

```javascript
require('operator-overloading/global');
```

<a name="paperscript"><sup>1</sup></a> Although, surprisingly, [this article](http://scratchdisk.com/posts/operator-overloading) suggests the performance hit isn't that large...

**Comment by kushal-likhi** [comment]
Hey, thanks! looks like a good idea. Agreed. :)
